import { Box, Text, Container, Image, Flex, Center } from "@chakra-ui/react";
import type { NextPage } from "next";
import  { useRouter } from "next/router";
import Head from "next/head";
import { Radio, Stack, RadioGroup } from "@chakra-ui/react";
import { useState } from "react";

const Home: NextPage = () => {
  const [value, setValue] = useState("0");
  const router = useRouter();

  const onSubmit = () => {
    if (value === "1") {
      router.push("/homepage");
    } else router.push("/artisan");
  };
  return (
    <Box>
      <Head>
        <title>Artisan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="160rem">
        <Flex justifyContent="center">
          <Box>
            <Center>
              <Image src="/assets/index/anywrk.svg" pt="8.1rem" alt="logo" />
            </Center>
            <Text
              fontFamily="fontbrand.Satoshi"
              mt="1.5rem"
              fontWeight="500"
              fontSize={{
                base: "3.0rem",
                md: "4.0rem",
              }}
            >
              What describes you?
            </Text>
          </Box>
        </Flex>
        <Center mt="4.0rem">
          <Box w="47.8rem">
            <RadioGroup onChange={setValue} value={value}>
              <Stack spacing="24px">
                <RadioContent
                  title="User"
                  valuestate="1"
                  description="Get unlimited access to artisans and also insert dummy text here"
                  colorscheme="blue"
                />
                <RadioContent
                  title="Artisan"
                  valuestate="2"
                  description="Get access to individuals / companies that need your expertise"
                  colorscheme="green"
                />
              </Stack>
            </RadioGroup>
            <Box
              onClick={onSubmit}
              mt="4.0rem"
              bgColor="brand.primary"
              borderRadius="10px"
            >
              <Text
                fontFamily="fontbrand.Satoshi"
                fontWeight="500"
                py="2.0rem"
                textAlign="center"
                fontSize="1.8rem"
                cursor="pointer"
                color="brand.white"
              >
                Continue
              </Text>
            </Box>
            <Text
              fontFamily="fontbrand.Satoshi"
              fontSize="1.8rem"
              textAlign="center"
              mt="4.0rem"
            >
              Already have an account? Sign in
            </Text>
          </Box>
        </Center>
      </Container>
    </Box>
  );
};

export default Home;

type radioContentProps = {
  title: string;
  valuestate: string;
  description: string;
  colorscheme: string;
};

const RadioContent = ({
  title,
  description,
  colorscheme,
  valuestate,
}: radioContentProps) => {
  return (
    <Flex p="1.6rem" border="1px" borderColor="#D9D9D9" borderRadius="10px">
      <Flex gap="1.5rem">
        <Box>
          <Radio
            sx={{
              width: "3rem",
              height: "3rem",
              marginTop: "0.5rem",
              fontSize: "2.4rem !important",
            }}
            value={`${valuestate}`}
            colorScheme={`${colorscheme}`}
          />
        </Box>
        <Box>
          <Text
            fontSize="2.4rem !important"
            fontFamily="fontbrand.Satoshi"
            fontWeight="500"
          >
            {title}
          </Text>
          <Text
            fontSize="1.8rem"
            fontFamily="fontbrand.Satoshi"
            color="color.textRadio"
          >
            {description}
          </Text>
        </Box>
      </Flex>
      <Box>
        <Radio
          sx={{
            width: "2rem",
            height: "2rem",
          }}
          name="1"
          colorScheme="red"
          isDisabled
        />
      </Box>
    </Flex>
  );
};
