import { Box, Text, Container, Image, Flex, Center } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

const Home: NextPage = () => {
  const [isColor, setColor] = useState(false);
  const [isBackColor, setBackColor] = useState(false);

  const ChangeColor = () => {
    setColor(!isColor);
  };

  const ChangeColor1 = () => {
    setBackColor(!isBackColor);
  };
  return (
    <Box>
      <Head>
        <title>Artisan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="160rem">
        <Box position="relative">
          <Flex position="absolute" mt="6.5rem" w="100%">
            <Box flex="46%"></Box>
            <Flex
              flex={{ base: "81%", md: "60%", lg: "54%" }}
              justifyContent="space-between"
            >
              <Flex>
                <Text
                  fontSize="3.0rem"
                  fontWeight="700"
                  fontFamily="'Satoshi', sans-serif"
                  // sx={{isColor  ? color : ""}}
                  color={isColor ? "#fff" : "#000"}
                >
                  Get
                </Text>
                <Text
                  fontSize="3.0rem"
                  fontWeight="700"
                  // ml = "2.5rem"
                  fontFamily="'Satoshi', sans-serif"
                  color={isBackColor ? "#fff" : "#000"}
                >
                  &nbsp;Started
                </Text>
              </Flex>
              <Image src="/assets/close.svg" alt="close-icon" />
            </Flex>
          </Flex>
        </Box>
        <Flex h="100vh">
          <Center
            flex="1"
            _hover={{
              background: "brand.CustomerColor",
            }}
            cursor="pointer"
            onMouseEnter={ChangeColor}
            onMouseLeave={ChangeColor}
          >
            <Link href="/homepage">
              <Box>
                <Text
                  fontFamily="'Satoshi', sans-serif"
                  textAlign="center"
                  fontSize="2.4rem"
                >
                  Sign up
                </Text>
                <Text
                  fontFamily="'Satoshi', sans-serif"
                  fontSize="3.0rem"
                  fontWeight="700"
                  whiteSpace="nowrap"
                >
                  As a customer
                </Text>
                <Center>
                  <Image src="/assets/arrow-right.svg" alt="close-icon" />
                </Center>
              </Box>
            </Link>
          </Center>

          <Center
            flex="1"
            _hover={{
              background: "brand.ArtisanColor",
            }}
            cursor="pointer"
            onMouseEnter={ChangeColor1}
            onMouseLeave={ChangeColor1}
          >
            <Link href="/homepage">
              <Box>
                <Text
                  fontFamily="'Satoshi', sans-serif"
                  fontSize="2.4rem"
                  textAlign="center"
                >
                  Sign up
                </Text>
                <Text
                  fontFamily="'Satoshi', sans-serif"
                  fontSize="3.0rem"
                  fontWeight="700"
                  whiteSpace="nowrap"
                >
                  As an artisan
                </Text>
                <Center>
                  <Image src="/assets/arrow-right.svg" alt="close-icon" />
                </Center>
              </Box>
            </Link>
          </Center>
        </Flex>
      </Container>
    </Box>
  );
};

export default Home;
